drss/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.urlpatterns import format_suffix_patterns
from drss import views

urlpatterns = patterns('drss.views',
                       url(r'^$', 'api_root'),
                       url(r'^projects/$', views.project_list, name='project-list'),
                       url(r'^real-estate/$', views.real_estate_list, name='real-estate-list'),
                       url(r'^real-estate/approval-queue$', views.site_approval_list, name='site-approval-list'),
                       url(r'^projects/create$', views.project_create, name='project_create'),
                       url(r'^comments/$', views.CommentList.as_view(), name='comment-list'),
                       url(r'^documents/$', views.DocumentList.as_view(), name='document-list'),
                       url(r'^payments/$', views.PaymentList.as_view(), name='payment-list'),
                       url(r'^funding-advisors/$', views.fundingadvisor_list, name='funding-advisor-list'),
                       url(r'^funding-advisors/(?P<user_id>\d+)/$', views.fundingadvisor_detail, name='fundingadvisor_detail'),
                       url(r'^salespeople/$', views.salesperson_list, name='salesperson_list'),
                       url(r'^salespeople/(?P<user_id>\d+)/$', views.salesperson_detail, name='salesperson_detail'),
                       url(r'^status/$', views.StatusList.as_view(), name='status-list'),
                       url(r'^projects/(?P<pk>\d+)/$', views.project_detail, name='project_detail'),
                       url(r'^api/projects/(?P<pk>\d+)/$', views.ProjectApi.as_view(), name='project_api'),
                       url(r'^documents/(?P<pk>\d+)/$', views.document_detail, name='document-detail'),
                       url(r'^loi/(?P<pk>\d+)/$', views.loi_detail, name='loi_detail'),
                       url(r'^projects/(?P<pk>\d+)/deposit/$', views.deposit_detail, name='deposit_detail'),
                       url(r'^projects/(?P<pk>\d+)/refund/$', views.process_refund, name='process_refund'),
                       url(r'^projects/(?P<pk>\d+)/turnover_to_re/$', views.turnover_to_re, name='process_turnover_to_re'),
                       url(r'^projects/(?P<pk>\d+)/sites/(?P<site_id>\d+)$', views.site_detail, name='site_detail'),
                       url(r'^projects/(?P<pk>\d+)/sites/$', views.site_create, name='create_site'),
                       url(r'^application/$', views.application, name='application'),
                       url(r'^sdl/$', views.sales_deposit_log, name='sales_deposit_log'),
                       url(r'^assign/finance/$', views.assign_finance, name='assign_finance'),
                       url(r'^refunds/$', views.refunds, name='refunds'),
                       url(r'^application/(?P<app_id>\d+)/$', views.application_detail, name='application_detail'),
                       url(r'^application/(?P<app_id>\d+)/deposit/$', views.deposit, name='deposit_pay'),
                       url(r'^application/(?P<app_id>\d+)/documents/$', views.submit_docs, name='submit_docs'),
                       url(r'^application/(?P<app_id>\d+)/print/$', views.print_app, name='print_app'),
                       url(r'^thankyou/$', views.thankyou, name='thankyou'),
                       url(r'^support/$', views.support, name='thankyou'),
                       url(r'^payment_hook$', views.payment_hook, name='payment_hook'),
                       url(r'^payment_complete/$', views.payment_complete, name='payment_complete'),
                       )

# Format suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['json', 'api'])

# Default login/logout views
urlpatterns += patterns('',
                        url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
                        )

task_manager/urls.py
from django.conf.urls import patterns, url
from task_manager import views

urlpatterns = patterns('task_manager.views',
                       url(r'^day-planner/$', views.day_planner, name='day-planner'),
                       url(r'^projects/(?P<pk>\d+)/tasks/$', views.create_task, name='task-list'),
                       url(r'^projects/(?P<pk>\d+)/emails/$', views.send_email, name='email-list'),
                       url(r'^projects/(?P<pk>\d+)/phonecalls/$', views.log_phone_call, name='email-list'),
                       url(r'^projects/(?P<pk>\d+)/tasks/(?P<taskid>\d+)/$', views.task_detail, name='task-detail'),
                       url(r'^creative/$', views.creative, name='creative'),
                       url(r'^creative/workproject/$', views.create_work_project, name='workproject-create'),
                       url(r'^creative/workproject/(?P<pk>\d+)/$', views.work_project_detail, name='workproject-detail'),
                       url(r'^creative/ticket/(?P<pk>\d+)/complete$', views.complete_ticket, name='ticket-complete'),
                       url(r'^creative/ticket/$', views.create_ticket, name='ticket-create'),
                       url(r'^creative/ticket/(?P<pk>\d+)/$', views.ticket_detail, name='ticket-detail'),
                       url(r'^creative/workproject/(?P<pk>\d+)/check-in/$', views.check_in, name='workproject-checkin'),
                       url(r'^creative/workproject/(?P<pk>\d+)/check-out/$', views.check_out, name='workproject-checkout'),
                       )

task_manager/models.py
from django.db import models
from datetime import timedelta
from django.contrib.auth.models import User
from templated_email import send_templated_mail
from drss.models import Project, Department, Comment
from datetime import date


class TaskType(models.Model):
    title = models.CharField(max_length=64)

    def __unicode__(self):
        return self.title


class Result(models.Model):
    title = models.CharField(max_length=64)
    quality = models.CharField(max_length=64)

    def __unicode__(self):
        return self.title


class ContactTemplate(models.Model):
    template_type = models.CharField(max_length=64)
    title = models.CharField(max_length=64)
    body = models.TextField(max_length=5000)

    def __unicode__(self):
        return self.title


class Task(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User,  related_name='contact_employee', verbose_name="Employee")
    project = models.ForeignKey(Project,  related_name='contact_project', verbose_name="Project", null=True, blank=True)
    template = models.ForeignKey(ContactTemplate,  related_name='email_template', verbose_name="Email Template", null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField(max_length=5000, null=True, blank=True)
    department = models.ForeignKey(Department,  related_name='department', verbose_name="Department", null=True, blank=True)
    task_type = models.ForeignKey(TaskType,  related_name='Task Type', verbose_name="Task Type", null=True)
    scheduled_date = models.DateField('Scheduled Date', null=True, blank=True)
    completion_date = models.DateField('Completion Date', null=True, blank=True)
    start_time = models.DateTimeField('Start Time', null=True, blank=True)
    end_time = models.DateTimeField('End Time', null=True, blank=True)
    completion_time = models.FloatField(null=True, blank=True, default=0)
    completion = models.BooleanField()
    result = models.ForeignKey(Result,  related_name='Result', verbose_name="Result", null=True, blank=True)
    recording = models.FileField(upload_to="documents", null=True, blank=True)

    def past_due(self):
        if date.today() > self.scheduled_date and not self.completion:
            return True
        else:
            return False

    def send_email(self):
        send_templated_mail(template_name='drss_sales',
                            from_email=self.user.email,
                            recipient_list=[self.project.email, 'steve.castle@drssmail.com'],
                            context={'subject': self.subject, 'body': self.body}
                            )

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        super(Task, self).save(*args, **kwargs)
        if self.body:
            body = self.body
            user = self.user
            project = self.project
            comment = Comment(body=body, author=user, internal=False, project=project)
            comment.save()

    def __unicode__(self):
        return self.title


class ProjectType(models.Model):
    title = models.CharField(max_length=200)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']


class ProjectStatus(models.Model):
    title = models.CharField(max_length=200)
    rank = models.IntegerField(null=True, blank=True)

    def __unicode__(self):
        return self.title


class WorkProject(models.Model):
    title = models.CharField(max_length=200)
    start_date = models.DateField('Start Date', null=True)
    due_date = models.DateField('Due Date', null=True)
    description = models.TextField(null=True, blank=True)
    completion = models.IntegerField(null=True, blank=True)
    priority = models.IntegerField(null=True, blank=True)
    status = models.ForeignKey(ProjectStatus, null=True, blank=True)
    project_type = models.ForeignKey(ProjectType, null=True)
    copy_link = models.CharField(max_length=300, null=True, blank=True)
    final_link = models.CharField(max_length=300, null=True, blank=True)
    note = models.CharField(max_length=300, null=True, blank=True)

    def users_working(self):
        users = ProjectUser.objects.all()
        wu = []
        for user in users:
            last_check_in = CheckIn.objects.filter(user=user.user).filter(work_project=self).order_by('-pk')
            if last_check_in and not last_check_in[0].check_type:
                wu.append(last_check_in[0].user)
            users_working = wu
        return users_working

    def project_time(self):
        checkins = CheckIn.objects.filter(work_project=self).filter(check_type=True)
        i = 0
        time = "0:0:0"
        for checkin in checkins:
            if i == 0:
                time = checkin.time_logged()
                i = i + 1
            else:
                time = time + checkin.time_logged()
        return time

    def __unicode__(self):
        return self.title


class ProjectUser(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    on_projects = models.ManyToManyField(WorkProject, null=True, blank=True, related_name='project_user')

    def __unicode__(self):
        return self.user.get_full_name()


class Ticket(models.Model):
    title = models.CharField(max_length=200)
    assigned_to = models.ForeignKey(ProjectUser, null=True, blank=True)
    belongs_to = models.ForeignKey(User, null=True, blank=True)
    start_time = models.DateTimeField('Start Date', null=True, auto_now_add=True)
    complete_time = models.DateTimeField('Completion Date', null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    status = models.ForeignKey(ProjectStatus, null=True, blank=True)
    project_type = models.ForeignKey(ProjectType, null=True)
    note = models.CharField(max_length=300, null=True, blank=True)

    def __unicode__(self):
        return self.title


class CheckIn(models.Model):
    work_project = models.ForeignKey(WorkProject,  related_name='checkin', verbose_name="Project")
    user = models.ForeignKey(ProjectUser)
    time = models.DateTimeField('Check In Time',  auto_now_add=True)
    check_type = models.BooleanField()
    completion = models.IntegerField(null=True, blank=True)
    note = models.CharField(max_length=300, null=True, blank=True)

    def time_logged(self):
        current = self.id
        user = self.user
        last_check_in = CheckIn.objects.filter(user=user).filter(pk__lt=current).filter(check_type=False).order_by('-pk')[0:1]
        if last_check_in:
            elapsed = self.time - last_check_in[0].time
        else:
            elapsed = "Check In"
        return elapsed

    def __unicode__(self):
        return self.user.user.get_full_name()

task_manager/forms.py
from django.forms import ModelForm, Form, FileField
from django.contrib.localflavor.us.forms import USSocialSecurityNumberField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, HTML, Fieldset, Hidden, Field
from crispy_forms.bootstrap import FormActions, AppendedPrependedText, AppendedText
from task_manager.models import Task, WorkProject, Ticket


class NewTask(ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewTask, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.layout = Layout(
            Fieldset('Create Task', 
                     'title',
                     'user',
                     'project',
                     'task_type',
                     'scheduled_date',
                     'start_time',
                     'end_time'),
            Hidden('time_specific', False),
            Hidden('completion', False),
            FormActions(
                Submit('submit', 'Submit', css_class='button white')
            )
        )

    class Meta:
        model = Task


class NewWorkProject(ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewWorkProject, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.layout = Layout(
            Fieldset('Create Project',
                     'title',
                     Field('start_date'),
                     Field('due_date'),
                     'status',
                     'project_type',
                     'copy_link',
                     'final_link'),
            FormActions(
                Submit('submit', 'Submit', css_class='button white')
            )
        )

    class Meta:
        model = WorkProject


class NewTicket(ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewTicket, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.layout = Layout(
            Fieldset('Create Project',
                     'title',
                     Field('description', css_class='input-block-level'),
                     'project_type',

                     ),
            FormActions(
                Submit('submit', 'Submit', css_class='button white')
            )
        )

    class Meta:
        model = Ticket


class NewEmail(ModelForm):
    def __init__(self, *args, **kwargs):
        super(NewEmail, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.form_method = 'post'
        self.helper.form_action = '#'
        self.helper.layout = Layout(
            Field('subject', css_class="input-block-level"),
            Field('body', css_class="input-block-level"),
            Hidden('completion', True),
            FormActions(
                Submit('submit', 'Send', css_class='button white')
            )
        )

    class Meta:
        model = Task

task_manager/templates/creative.html
{% extends 'base.html' %}
 {%load humanize%}
{%block secondarynav%}
<div class="navbar">
  <div class="navbar-inner">
    <ul class="nav">
      <li><a href="ticket" ><i class="icon-question-sign"></i>Request Ticket</a> </li>
      <li><a href="workproject"><i class="icon-plus"></i>Add a Project</a> </li>
      <li><a href="http://10.1.0.61/MediaWiki/index.php/Main_Page" target="_blank"><i class="icon-book"></i>Creative Library</a></li>
    </ul>
  </div>
</div>
{%endblock%}
{% block content %}
    <div class="span12">
<div class="page-header">
<h1>Creative Department Dash Board</h1>
</div>
<ul class="nav nav-tabs" id="myTab">
    <li class="active"><a href="#projects" data-toggle="tab">Projects</a></li>
    <li><a href="#tickets" data-toggle="tab">Tickets</a></li>
    <li><a href="#recurring" data-toggle="tab">Recurring</a></li>
<li><a href="#reports" data-toggle="tab">Reports</a></li>
  </ul>

  <div class="tab-content">

    <div class="tab-pane active" id="projects">
        <div class="well">
        {{ projectsfilter }}
    </div>
<table class="table" id="projectTable">
<thead>
    <tr>
    <th data-sort="string">Project</th>
    <th data-sort="string">Priority</th>
    <th><i class="icon-calendar"></i> Assigned Date</th>
    <th><i class="icon-time"></i> Due Date</th>
    <th data-sort="string"><i class="icon-user"></i> People</th>
    <th><i class="icon-time"></i> Completion</th>
    <th><i class="icon-flag"></i> Recap</th>
</tr>
</thead>
<tbody>
    {% for work_project in work_projects%}
    <tr {% if work_projects.past_due %}class="error"{% endif %}>
<td><a href="/creative/workproject/{{work_project.id}}/">{{work_project.title}}</a></td>
<td>{{work_project.status}}</td>
<td>{{work_project.start_date}}</td>
<td>{{work_project.due_date}}</td>
<td>{% for person in work_project.project_user.all%}{{person}} {% endfor %}</td>
<td><div class="progress progress-striped">
                    <div class="bar" style="width: {{work_project.completion}}%"></div></div></td>
<td>{{work_project.note}}</td>
    </tr>
    {%endfor%}
</tbody>
</table>
    </div>

    <div class="tab-pane" id="tickets">
<table class="table">
<thead>
    <tr>
    <th>Ticket</th>
    <th><i class="icon-time"></i>Requested</th>
    <th><i class="icon-user"></i>Assigned To</th>
    <th><i class="icon-user"></i>For</th>
    <th><i class="icon-flag"></i>Recap</th>
</tr>
</thead>
<tbody>
    {% for ticket in tickets%}
    <tr {% if ticket.past_due %}class="error"{% endif %}>
<td><a href="/creative/ticket/{{ticket.id}}/">{{ticket.title}}</a></td>
<td>{{ticket.start_time}}</td>
<td>{{ticket.assigned_to}}</td>
<td>{{ticket.belongs_to}}</td>
<td>{{ticket.note}}</td>

    </tr>
    {%endfor%}
    <tr>
            <th>Ticket</th>
    <th><i class="icon-time"></i>Completed</th>
    <th><i class="icon-user"></i>Assigned To</th>
    <th><i class="icon-user"></i>For</th>
    <th><i class="icon-flag"></i>Recap</th>
    </tr>
        {% for ticket in complete_tickets%}
    <tr>
<td><a href="/creative/ticket/{{ticket.id}}/">{{ticket.title}}</a></td>
<td>{{ticket.complete_time}}</td>
<td>{{ticket.assigned_to}}</td>
<td>{{ticket.belongs_to}}</td>
<td>{{ticket.note}}</td>

    </tr>
    {%endfor%}
</tbody>
</table>

    </div>

    <div class="tab-pane" id="recurring">
        
        <h2>Week 6/17/2013 to 6/21/2013</h2>
        <div class="row">
        <div class="span2">
            <h3>Monday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr class="error">
                        <td>Send an NSO</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span2">
            <h3>Tuesday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr class="success">
                        <td>Send TemeSeminar Reminder</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span2">
            <h3>Wednesday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr class="success">
                        <td>Create Web Leads Report</td>
                    </tr>
                    <tr class="success">
                        <td>Create Phone Report</td>
                    </tr>
                    <tr class="error">
                        <td>Create Chat Report</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span2">
            <h3>Thursday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                                        <tr class="warning">
                        <td >Add New Leads to Drip</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span2">
            <h3>Friday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr class="error">
                        <td>Send an NSO</td>
                    </tr>
                    <tr class="warning">
                        <td>Generate Teleseminar Report</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <hr>
        <h2>Week 6/24/2013 to 6/28/2013</h2>
        <div class="row">
        <div class="span2">
            <h3>Monday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr>
                        <td>Send an NSO</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span2">
            <h3>Tuesday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr class="success">
                        <td>Send TemeSeminar Reminder</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span2">
            <h3>Wednesday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr class="success">
                        <td>Create Web Leads Report</td>
                    </tr>
                    <tr class="success">
                        <td>Create Phone Report</td>
                    </tr>
                    <tr class="warning">
                        <td>Create Chat Report</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span2">
            <h3>Thursday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr class="success">
                        <td>Add New Leads to Drip</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="span2">
            <h3>Friday</h3>
            <table class="table table-striped">
                <tbody>
                    <tr class="success">
                        <td>Finance Migration</td>
                    </tr>
                    <tr class="success">
                        <td>Process Web Leads</td>
                    </tr>
                    <tr class="success">
                        <td>Distribute E-Mail Responses</td>
                    </tr>
                    <tr class="success">
                        <td>Send an NSO</td>
                    </tr>
                    <tr class="success">
                        <td>Generate Teleseminar Report</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    </div>
    <div class="tab-pane" id="reports">

    </div>

  </div>
</div>
{% endblock %}

task_manager/templates/day-planner.html
{% extends 'base.html' %}
 {%load humanize%}
{%block message%}
{% if not tasks %}
<div class="alert alert-info">
 <strong>Congratulations</strong>, take the day off. You do not have any past due or currently due tasks. 
</div>
{% endif %}
{%endblock%}
{% block content %}
<div class="page-header">
<h1>My Activities<small> for {{date}}</small></h1>
</div>
<table class="table">
<thead>
	<tr>
	<th><i class="icon-calendar"></i> Due Date</th>
    <th><i class="icon-time"></i> Time</th>
	<th><i class="icon-tags"></i> Type</th>
    <th><i class="icon-user"></i> For Client</th>
	<th>Title</th>
	<th><i class="icon-time"></i> Estimated Time</th>
	<th><i class="icon-flag"></i> Result</th>
</tr>
</thead>
<tbody>
	{% for task in tasks%}
    <tr {% if task.past_due %}class="error"{% endif %}>
        <td>{{task.scheduled_date}}</td>
        <td>{{task.start_time}}</td>
        <td><img src="/static/img/{{task.task_type}}.png" alt="{{task.task_type}}"></td>
        <td><a href = "/projects/{{task.project.id}}">{{task.project.full_name}}</a></td>
        <td><a href = "/projects/{{task.project.id}}/tasks/{{task.id}}">{{task.title}}</a></td>
        <td>{% if task.completion_time %}{{task.completion_time|apnumber}} minutes {% endif%}</td>
        {%if task.result.title%}
        <td><span class="label label-{{task.result.quality}}">{{task.result.title}}</span></td>
        {% else %}
         <td><span class="label label-important">Not Completed</span></td>
         {%endif%}
    </tr>
	{%endfor%}
</tbody>
</table>
{% endblock %}

task_manager/templates/email-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block breadcrumbs %}
 <ul class="breadcrumb">
  <li><a href="/projects">Projects</a> <span class="divider">/</span></li>
  <li><a href="/projects/{{project.id}}/#contact-history">{{project.full_name}}</a> <span class="divider">/</span></li>
  <li class="active">Send Email</li>
</ul>
{% endblock %}

{% block content %}
<h4>From: {{user.email}}</h4>
<h4>To: {{project.email}}</h4>
<ul class="nav nav-pills">
{% for template in templates %}
  <li><a href="#" class="email-template" data-template="{{template.body}}">{{template.title}}</a></li>
{% endfor %}
</ul>
<form action="#" class="form-horizontal" method="post" enctype="multipart/form-data">{% csrf_token %}
  <div id="div_id_subject" class="control-group">
  <label for="id_subject" class="control-label ">
        Subject
      </label>
      <div class="controls">
        <input id="id_subject" type="text" class="input-block-level textinput textInput" name="subject" maxlength="200"> 
      </div>
      </div>
      <div id="div_id_body" class="control-group">
        <label for="id_body" class="control-label ">
        Body
      </label>
      <div class="controls">
        <textarea id="id_body" rows="10" cols="40" name="body" class="input-block-level textarea">
          
        </textarea>
      </div>
    </div>

    <input type="submit" name="submit" value="Send" class="btn btn-large btn-primary btn-block" id="submit-id-submit"> 
</form>
{% endblock %}

task_manager/templates/phonecall-create.html
{% extends 'base.html' %}
 {%load phone_number%}
{% block breadcrumbs %}
 <ul class="breadcrumb">
  <li><a href="/projects">Projects</a> <span class="divider">/</span></li>
  <li><a href="/projects/{{project.id}}/#contact-history">{{project.full_name}}</a> <span class="divider">/</span></li>
  <li class="active">Send Email</li>
</ul>
{% endblock %}

{% block content %}

<h3>{{project.home_phone|phone_number}}</h3>
<p>{{task.body}}</p>
<form method="post">{% csrf_token %}
<h4>Call Topic</h4>
<input id="id_subject" type="text" class="input-block-level textinput textInput" name="subject" maxlength="200">
<h4>Call Note</h4>
<textarea rows="3" class="input-block-level" name="body"></textarea>
<button class="btn btn-large btn-block btn-primary" type="submit" name="result" value="5">Phone Call Complete</button>
<button class="btn btn-large btn-block btn-warning" type="submit" name="result" value="2">Left Message</button>
</form>
{% endblock %}

task_manager/templates/task-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
 <ul class="breadcrumb">
  <li><a href="/projects">Projects</a> <span class="divider">/</span></li>
  <li><a href="/projects/{{project.id}}/#contact-history">{{project.full_name}}</a> <span class="divider">/</span></li>
  <li class="active">Create Task</li>
</ul>
{% endblock %}
{% block content %}
   {% crispy form %}
{% endblock %}

task_manager/templates/workproject-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
 <ul class="breadcrumb">
  <li><a href="/creative">Creative</a> <span class="divider">/</span></li>
    <li class="active">Create Task</li>
</ul>
{% endblock %}
{% block content %}
   {% crispy form %}
{% endblock %}